<#
  generate-manifest.ps1
  ---------------------
  Scans the images\ and sounds\ folders and writes manifest.js + manifest.json,
  so new backgrounds / adhan files appear in Settings automatically.

  Optional: also creates images\optimized\ (max 2560 px, for smooth TVs) and
  images\thumbs\ (400 px, for the Settings picker) for any image that doesn't
  have them yet.

  Usage (from this folder):
      powershell -ExecutionPolicy Bypass -File .\generate-manifest.ps1
      powershell -ExecutionPolicy Bypass -File .\generate-manifest.ps1 -SkipResize

  Friendly names: keep the existing "name" for files already in manifest.json;
  new files get a name derived from the file name (e.g. "blue-mosque.jpg" -> "Blue Mosque").
#>
param([switch]$SkipResize)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

function Get-FriendlyName([string]$file) {
  $n = [IO.Path]::GetFileNameWithoutExtension($file) -replace '[-_]+', ' '
  return (Get-Culture).TextInfo.ToTitleCase($n.ToLower())
}

# Keep names/descriptions the user already edited
$old = @{}
if (Test-Path 'manifest.json') {
  try {
    $j = Get-Content 'manifest.json' -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($x in @($j.images) + @($j.sounds)) { if ($x -and $x.filename) { $old[$x.filename] = $x } }
  } catch { Write-Warning "Could not read existing manifest.json - names will be regenerated." }
}

Add-Type -AssemblyName System.Drawing -ErrorAction SilentlyContinue
function Save-Resized([string]$src, [string]$dst, [int]$max, [long]$quality) {
  $img = [System.Drawing.Image]::FromFile($src)
  try {
    $k = [Math]::Min(1.0, $max / [Math]::Max($img.Width, $img.Height))
    $w = [int]($img.Width * $k); $h = [int]($img.Height * $k)
    $bmp = New-Object System.Drawing.Bitmap $w, $h
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = 'HighQualityBicubic'; $g.DrawImage($img, 0, 0, $w, $h); $g.Dispose()
    $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
    $ep = New-Object System.Drawing.Imaging.EncoderParameters 1
    $ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter ([System.Drawing.Imaging.Encoder]::Quality), $quality
    $bmp.Save($dst, $codec, $ep); $bmp.Dispose()
  } finally { $img.Dispose() }
}

$images = @()
New-Item -ItemType Directory -Force -Path 'images\optimized', 'images\thumbs' | Out-Null
Get-ChildItem 'images' -File | Where-Object { $_.Extension -match '^\.(jpe?g|png|webp)$' } | Sort-Object Name | ForEach-Object {
  $f = $_.Name
  $opt = Join-Path 'images\optimized' $f; $th = Join-Path 'images\thumbs' $f
  if (-not $SkipResize -and $_.Extension -match '^\.(jpe?g|png)$') {
    try {
      if (-not (Test-Path $opt)) { Save-Resized $_.FullName (Join-Path $root $opt) 2560 80; Write-Host "  optimized $f" }
      if (-not (Test-Path $th))  { Save-Resized $_.FullName (Join-Path $root $th) 400 75;  Write-Host "  thumbnail $f" }
    } catch { Write-Warning "Could not resize $f : $_" }
  }
  $name = if ($old[$f]) { $old[$f].name } else { Get-FriendlyName $f }
  $images += [ordered]@{ id = [IO.Path]::GetFileNameWithoutExtension($f); name = $name; filename = $f
    optimized = (Test-Path $opt); thumb = (Test-Path $th); description = $name }
}

$sounds = @()
Get-ChildItem 'sounds' -File | Where-Object { $_.Extension -match '^\.(mp3|m4a|aac|wav|ogg|oga|opus)$' } | Sort-Object Name | ForEach-Object {
  $f = $_.Name
  $name = if ($old[$f]) { $old[$f].name } else { Get-FriendlyName $f }
  $o = [ordered]@{ id = [IO.Path]::GetFileNameWithoutExtension($f); name = $name; filename = $f; description = $name }
  if ($old[$f] -and $old[$f].duration) { $o.duration = $old[$f].duration }
  $sounds += $o
}

$manifest = [ordered]@{ generated = (Get-Date -Format 'yyyy-MM-dd'); images = $images; sounds = $sounds }
$json = $manifest | ConvertTo-Json -Depth 5
$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText((Join-Path $root 'manifest.json'), $json + "`n", $utf8)
[IO.File]::WriteAllText((Join-Path $root 'manifest.js'), "// Auto-generated by generate-manifest.ps1 - lets the app work when opened directly from disk (file://)`nwindow.PRAYER_MANIFEST = $json;`n", $utf8)
Write-Host "manifest.js / manifest.json written: $($images.Count) images, $($sounds.Count) sounds"
