// Auto-generated by generate-manifest.ps1 — lets the app work when opened directly from disk (file://)
window.PRAYER_MANIFEST = {
  "generated": "2026-10-02",
  "images": [
    {
      "id": "Image001",
      "name": "White Marble Courtyard",
      "filename": "Image001.jpg",
      "optimized": true,
      "thumb": true,
      "description": "White Marble Courtyard"
    },
    {
      "id": "Image002",
      "name": "Modern Mosque, Blue Sky",
      "filename": "Image002.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Modern Mosque, Blue Sky"
    },
    {
      "id": "Image003",
      "name": "Lakeside Reflection",
      "filename": "Image003.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Lakeside Reflection"
    },
    {
      "id": "Image004",
      "name": "Golden Arches at Dusk",
      "filename": "Image004.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Golden Arches at Dusk"
    },
    {
      "id": "Image005",
      "name": "Grand Mosque, Blue Sky",
      "filename": "Image005.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Grand Mosque, Blue Sky"
    },
    {
      "id": "Image006",
      "name": "Sunset Silhouette",
      "filename": "Image006.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Sunset Silhouette"
    },
    {
      "id": "Image007",
      "name": "White Domes, Morning",
      "filename": "Image007.jpg",
      "optimized": true,
      "thumb": true,
      "description": "White Domes, Morning"
    },
    {
      "id": "Image008",
      "name": "Madinah Courtyard",
      "filename": "Image008.jpg",
      "optimized": true,
      "thumb": true,
      "description": "Madinah Courtyard"
    }
  ],
  "sounds": [
    {
      "id": "sound001",
      "name": "Adhan 1",
      "filename": "sound001.mp3",
      "duration": "3:06",
      "description": "Adhan 1 (3:06)"
    },
    {
      "id": "sound002",
      "name": "Adhan 2",
      "filename": "sound002.mp3",
      "duration": "3:21",
      "description": "Adhan 2 (3:21)"
    },
    {
      "id": "sound003",
      "name": "Adhan 3",
      "filename": "sound003.mp3",
      "duration": "2:08",
      "description": "Adhan 3 (2:08)"
    }
  ]
};
