#!/usr/bin/env node
/* Netlify build (also works locally:  node scripts/build.mjs)
   1. Scans images/ and sounds/ and writes manifest.json + manifest.js
      (keeps friendly names already in manifest.json; new files get a name from the file name).
   2. If the optional "sharp" package is installed, creates images/optimized (≤2560 px) and
      images/thumbs (400 px) for new images. Without sharp, the original image is used.
      On GitHub, the "Resize new images" workflow (.github/workflows/resize-images.yml) installs
      sharp, runs this script and commits the resized copies, so Netlify never needs sharp.
   3. Copies only what the site needs into dist/ (originals are left out when a resized copy exists).
   No other dependencies. */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const dist = path.join(root, 'dist');
const IMG = /\.(jpe?g|png|webp)$/i, SND = /\.(mp3|m4a|aac|wav|ogg|oga|opus)$/i;
const exists = p => fs.access(p).then(() => true, () => false);
const friendly = f => path.parse(f).name.replace(/[-_]+/g, ' ').replace(/\s+/g, ' ').trim().replace(/\b\w/g, c => c.toUpperCase());
const list = async (dir, re) => (await exists(dir) ? (await fs.readdir(dir, { withFileTypes: true })).filter(d => d.isFile() && re.test(d.name)).map(d => d.name).sort() : []);

for (const must of ['index.html', 'sw.js']) if (!(await exists(path.join(root, must)))) { console.error(`✗ ${must} is missing from the repository — upload it and deploy again.`); process.exit(1); }
let sharp = null;   // optional: install "sharp" yourself to auto-resize new images
try { sharp = (await import('sharp')).default; } catch { console.log('ℹ Image resizing skipped (optional "sharp" package not installed) — new images are published at original size until the GitHub "Resize new images" workflow commits resized copies.'); }

const old = {};
try { const j = JSON.parse(await fs.readFile(path.join(root, 'manifest.json'), 'utf8')); for (const x of [...(j.images || []), ...(j.sounds || [])]) if (x && x.filename) old[x.filename] = x; } catch { }

const images = [];
for (const f of await list(path.join(root, 'images'), IMG)) {
  const src = path.join(root, 'images', f), opt = path.join(root, 'images', 'optimized', f), th = path.join(root, 'images', 'thumbs', f);
  if (sharp && /\.(jpe?g|png|webp)$/i.test(f)) {
    try {
      await fs.mkdir(path.dirname(opt), { recursive: true }); await fs.mkdir(path.dirname(th), { recursive: true });
      if (!(await exists(opt))) { await sharp(src).rotate().resize({ width: 2560, height: 2560, fit: 'inside', withoutEnlargement: true }).jpeg({ quality: 80, progressive: true, mozjpeg: true }).toFile(opt); console.log('  optimized', f); }
      if (!(await exists(th))) { await sharp(src).rotate().resize({ width: 400, height: 400, fit: 'inside' }).jpeg({ quality: 75 }).toFile(th); console.log('  thumbnail', f); }
    } catch (e) { console.warn('  could not resize', f, e.message); }
  }
  const o = old[f] || {}; const name = o.name || friendly(f);
  images.push({ id: path.parse(f).name, name, filename: f, optimized: await exists(opt), thumb: await exists(th), description: o.description || name });
}
const sounds = [];
for (const f of await list(path.join(root, 'sounds'), SND)) {
  const o = old[f] || {}; const name = o.name || friendly(f);
  sounds.push({ id: path.parse(f).name, name, filename: f, ...(o.duration ? { duration: o.duration } : {}), description: o.description || name });
}
const manifest = { generated: new Date().toISOString().slice(0, 10), images, sounds };
const json = JSON.stringify(manifest, null, 2);
await fs.writeFile(path.join(root, 'manifest.json'), json + '\n');
await fs.writeFile(path.join(root, 'manifest.js'), `// Auto-generated by scripts/build.mjs — lets the app work when opened directly from disk (file://)\nwindow.PRAYER_MANIFEST = ${json};\n`);
console.log(`✓ manifest: ${images.length} images, ${sounds.length} sounds`);

// ---- dist/
await fs.rm(dist, { recursive: true, force: true });
const copy = async (rel) => {
  const from = path.join(root, rel), to = path.join(dist, rel);
  if (!(await exists(from))) { console.warn('  ⚠ missing, skipped:', rel); return; }
  await fs.mkdir(path.dirname(to), { recursive: true }); await fs.copyFile(from, to);
};
for (const f of ['index.html', 'manifest.json', 'manifest.js', 'app.webmanifest']) await copy(f);
for (const f of await list(path.join(root, 'icons'), /\.(png|svg|ico)$/i)) await copy(path.join('icons', f));
for (const img of images) {
  if (img.optimized) await copy(path.join('images', 'optimized', img.filename)); else await copy(path.join('images', img.filename));
  if (img.thumb) await copy(path.join('images', 'thumbs', img.filename));
}
for (const s of sounds) await copy(path.join('sounds', s.filename));
// Service worker: stamp a content hash so browsers pick up new versions promptly
const hash = crypto.createHash('sha1').update(await fs.readFile(path.join(root, 'index.html'))).update(json).digest('hex').slice(0, 10);
const sw = (await fs.readFile(path.join(root, 'sw.js'), 'utf8')).replace(/const VERSION = '[^']*';/, `const VERSION = '${hash}';`);
await fs.writeFile(path.join(dist, 'sw.js'), sw);
console.log(`✓ dist/ ready (version ${hash})`);
